/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import InternalPages.Customer;
import config.DBconnector;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rhai
 */
public class CustomerFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        initComponents();
    }
    
    Color hovbtn = new Color(69,60,240);
    Color defbtn = new Color(126,120,240);
    
    public String action;
    
    public void close(){
        this.dispose();
        DashboardFrame df = new DashboardFrame();
        df.setVisible(true);
        Customer up = new Customer();
        df.desk_pnl.add(up).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_pnl = new javax.swing.JPanel();
        custid_inp = new javax.swing.JTextField();
        custfname_inp = new javax.swing.JTextField();
        custlname_inp = new javax.swing.JTextField();
        custemail_inp = new javax.swing.JTextField();
        custphone_inp = new javax.swing.JTextField();
        custcity_inp = new javax.swing.JTextField();
        custstate_inp = new javax.swing.JTextField();
        custpostal_inp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        custbarangay_inp = new javax.swing.JTextArea();
        imgbg_pnl = new javax.swing.JPanel();
        custimg_display = new javax.swing.JLabel();
        choose_btn = new javax.swing.JPanel();
        choose_lbl = new javax.swing.JLabel();
        action_btn = new javax.swing.JPanel();
        action_lbl = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();
        Image_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BG_pnl.setBackground(new java.awt.Color(204, 202, 240));
        BG_pnl.setPreferredSize(new java.awt.Dimension(850, 550));
        BG_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custid_inp.setEditable(false);
        custid_inp.setBackground(new java.awt.Color(204, 202, 240));
        custid_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custid_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Customer ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        BG_pnl.add(custid_inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 320, 50));

        custfname_inp.setBackground(new java.awt.Color(204, 202, 240));
        custfname_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custfname_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        BG_pnl.add(custfname_inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 320, 50));

        custlname_inp.setBackground(new java.awt.Color(204, 202, 240));
        custlname_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custlname_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Last Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        BG_pnl.add(custlname_inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 320, 50));

        custemail_inp.setBackground(new java.awt.Color(204, 202, 240));
        custemail_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custemail_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        BG_pnl.add(custemail_inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 320, 50));

        custphone_inp.setBackground(new java.awt.Color(204, 202, 240));
        custphone_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custphone_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Phone No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        custphone_inp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                custphone_inpKeyTyped(evt);
            }
        });
        BG_pnl.add(custphone_inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 320, 50));

        custcity_inp.setBackground(new java.awt.Color(204, 202, 240));
        custcity_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custcity_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "City", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        BG_pnl.add(custcity_inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 320, 50));

        custstate_inp.setBackground(new java.awt.Color(204, 202, 240));
        custstate_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custstate_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "State", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        BG_pnl.add(custstate_inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 320, 50));

        custpostal_inp.setBackground(new java.awt.Color(204, 202, 240));
        custpostal_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custpostal_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Postal Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        custpostal_inp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                custpostal_inpKeyTyped(evt);
            }
        });
        BG_pnl.add(custpostal_inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 320, 50));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        custbarangay_inp.setBackground(new java.awt.Color(204, 202, 240));
        custbarangay_inp.setColumns(20);
        custbarangay_inp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custbarangay_inp.setRows(5);
        custbarangay_inp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Barangay", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jScrollPane1.setViewportView(custbarangay_inp);

        BG_pnl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 320, 140));

        imgbg_pnl.setBackground(new java.awt.Color(126, 120, 240));
        imgbg_pnl.setPreferredSize(new java.awt.Dimension(200, 150));
        imgbg_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custimg_display.setPreferredSize(new java.awt.Dimension(150, 150));
        imgbg_pnl.add(custimg_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, -1, -1));

        BG_pnl.add(imgbg_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        choose_btn.setBackground(new java.awt.Color(126, 120, 240));
        choose_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        choose_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        choose_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choose_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choose_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choose_btnMouseExited(evt);
            }
        });

        choose_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        choose_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choose_lbl.setText("Choose a file...");

        javax.swing.GroupLayout choose_btnLayout = new javax.swing.GroupLayout(choose_btn);
        choose_btn.setLayout(choose_btnLayout);
        choose_btnLayout.setHorizontalGroup(
            choose_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(choose_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        choose_btnLayout.setVerticalGroup(
            choose_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(choose_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        BG_pnl.add(choose_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 200, 50));

        action_btn.setBackground(new java.awt.Color(126, 120, 240));
        action_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        action_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        action_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                action_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                action_btnMouseExited(evt);
            }
        });

        action_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        action_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout action_btnLayout = new javax.swing.GroupLayout(action_btn);
        action_btn.setLayout(action_btnLayout);
        action_btnLayout.setHorizontalGroup(
            action_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(action_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        action_btnLayout.setVerticalGroup(
            action_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(action_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG_pnl.add(action_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 200, 50));

        close_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_btn.setText("X");
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });
        BG_pnl.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        Image_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Image_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Image_lbl.setText("Image");
        BG_pnl.add(Image_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 50, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public  ImageIcon ResizeImage(String ImagePath, byte[] pic) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(custimg_display.getWidth(), custimg_display.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}

    public byte[] imageBytes;
    String path;
    String filename=null;
    String imgPath = null;
    public byte[] person_image = null;
    
    private void choose_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choose_btnMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        chooser.addChoosableFileFilter(filter);
        int result = chooser.showSaveDialog(null);
        
        if (result == JFileChooser.APPROVE_OPTION){
            File selectedFile = chooser.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            custimg_display.setIcon(ResizeImage(path,null));
            imgPath = path;
            File f = chooser.getSelectedFile();
            filename = selectedFile.getAbsolutePath();
        }else{
        JOptionPane.showMessageDialog(null, "Canceled !");
        }
        
      
        try {
                File image = new File(filename);
                FileInputStream fis = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                
                for (int readNum; (readNum=fis.read(buf)) !=-1;){
                 bos.write(buf,0,readNum);
                }
                person_image=bos.toByteArray();
                
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_choose_btnMouseClicked

    private void choose_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choose_btnMouseEntered
        choose_btn.setBackground(hovbtn);
    }//GEN-LAST:event_choose_btnMouseEntered

    private void choose_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choose_btnMouseExited
        choose_btn.setBackground(defbtn);
    }//GEN-LAST:event_choose_btnMouseExited

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        close();
    }//GEN-LAST:event_close_btnMouseClicked

    private void action_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action_btnMouseClicked
        if(action.equals("Add")){
           try{
            DBconnector dbc = new DBconnector();
            Connection con = dbc.connect_db();
            String sql = "INSERT INTO tbl_customer (first_name, last_name, email, phone_number, barangay, city, state, postal_code, customer_image) VALUES (?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, custfname_inp.getText());
            pst.setString(2, custlname_inp.getText());
            pst.setString(3, custemail_inp.getText());
            pst.setString(4, custphone_inp.getText());
            pst.setString(5, custbarangay_inp.getText());
            pst.setString(6, custcity_inp.getText());
            pst.setString(7, custstate_inp.getText());
            pst.setString(8, custpostal_inp.getText());
            pst.setBytes(9, person_image);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Updated!");
            
            close();
            
        }catch(Exception e){
            System.out.println(e);
        }
           
           
       }else if(action.equals("Update")){
            try {
                DBconnector dbc = new DBconnector();
                String custid = custid_inp.getText();
                String custfname = custfname_inp.getText();
                String custlname = custlname_inp.getText();
                String custemail = custemail_inp.getText();
                String custphone = custphone_inp.getText();
                String custaddress = custbarangay_inp.getText();
                String custcity = custcity_inp.getText();
                String custstate = custstate_inp.getText();
                String custpostal = custpostal_inp.getText();

                InputStream is = null;
                PreparedStatement pst = null;

                if (path == null || path.equals("")) {
                    // No new image selected, update only the other fields
                    pst = dbc.connect.prepareStatement("UPDATE tbl_customer SET first_name = ?, last_name = ?, email = ?, phone_number = ?, barangay = ?, city = ?, state = ?, postal_code = ? WHERE customer_id = ?");
                    pst.setString(1, custfname);
                    pst.setString(2, custlname);
                    pst.setString(3, custemail);
                    pst.setString(4, custphone);
                    pst.setString(5, custaddress);
                    pst.setString(6, custcity);
                    pst.setString(7, custstate);
                    pst.setString(8, custpostal);
                    pst.setString(9, custid);
                    
                } else {
                    // New image selected, update the image and the path
                    File f = new File(path);
                    is = new FileInputStream(f);
                    pst = dbc.connect.prepareStatement("UPDATE tbl_customer SET customer_image = ?, first_name = ?, last_name = ?, email = ?, phone_number = ?, barangay = ?, city = ?, state = ?, postal_code = ? WHERE customer_id = ?");
                    pst.setBlob(1, is);
                    pst.setString(2, custfname);
                    pst.setString(3, custlname);
                    pst.setString(4, custemail);
                    pst.setString(5, custphone);
                    pst.setString(6, custaddress);
                    pst.setString(7, custcity);
                    pst.setString(8, custstate);
                    pst.setString(9, custpostal);
                    pst.setString(10, custid);

                }

                int inserted = pst.executeUpdate();

                if (inserted > 0) {
                    JOptionPane.showMessageDialog(null, "Customer information successfully updated!");
                }

                // Close the prepared statement and input stream
                if (pst != null) {
                    pst.close();
                }
                if (is != null) {
                    is.close();
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ProductFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ProductFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ProductFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            close();
       }
    }//GEN-LAST:event_action_btnMouseClicked
    
    private void action_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action_btnMouseEntered
        action_btn.setBackground(hovbtn);
    }//GEN-LAST:event_action_btnMouseEntered

    private void action_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action_btnMouseExited
       action_btn.setBackground(defbtn);
    }//GEN-LAST:event_action_btnMouseExited

    private void custphone_inpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custphone_inpKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_custphone_inpKeyTyped

    private void custpostal_inpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custpostal_inpKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_custpostal_inpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_pnl;
    private javax.swing.JLabel Image_lbl;
    private javax.swing.JPanel action_btn;
    public javax.swing.JLabel action_lbl;
    private javax.swing.JPanel choose_btn;
    private javax.swing.JLabel choose_lbl;
    private javax.swing.JLabel close_btn;
    public javax.swing.JTextArea custbarangay_inp;
    public javax.swing.JTextField custcity_inp;
    public javax.swing.JTextField custemail_inp;
    public javax.swing.JTextField custfname_inp;
    public javax.swing.JTextField custid_inp;
    public javax.swing.JLabel custimg_display;
    public javax.swing.JTextField custlname_inp;
    public javax.swing.JTextField custphone_inp;
    public javax.swing.JTextField custpostal_inp;
    public javax.swing.JTextField custstate_inp;
    private javax.swing.JPanel imgbg_pnl;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
